name: prescription_config
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  share_plus: ^10.1.2
  quill_html_editor: ^2.2.8
  package_info_plus: ^8.1.1
  fluttertoast: ^8.2.8
  pdf_render: ^1.4.12
  downloadsfolder: ^1.1.0
  flutter_widget_from_html_core: ^0.15.2
  path_provider: ^2.1.5
  html_to_pdf: ^0.8.1
  media_scanner:
    git:
      url: https://github.com/wukgdu/media_scanner.git
      ref: efe757c

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_lints: ^5.0.0
  #lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 700

    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 700

    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 300
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 700